#!/bin/bash
if test $# -eq 0 || test "$1" = "tools"
then
	BASE="$( cd .. -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
else
	BASE="${1:-./}"
fi
BIN_DIR="../../../../sgm-nodejs/tools"
SPECS="${2:-$BASE/specs}"
DATA="${3:-$BASE/data}"

echo "raw -> csv" &&
node $BIN_DIR/raw2csv.js -i "$DATA/raw" -o "$DATA/csv" -m "$SPECS/mappings.json" &&
echo "csv -> json" &&
node $BIN_DIR/csv2json.js -i "$DATA/csv" -o "$DATA/json" -m "$SPECS/mappings.json" &&
# not working yet!
echo "json -> hal" &&
node $BIN_DIR/json2hal.js -i "$DATA/json" -o "$DATA/hal" -t "$SPECS/transforms.json"